version: '3.8'

services:
  pypi-server:
    container_name: pypi-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/app/site
      - ./dist:/app/dist
      - ./packages:/app/packages
    ports:
      - "8080:8080"
    command: ["pypi-server", "run", "-p", "8080", "-v", "--log-file", "/dev/stdout", "site"]

